# Generated by Django 6.0.4 on 2026-04-30 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth_app.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_encrypted', models.TextField()),
                ('treatmentPlan_encrypted', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_app.encounter')),
            ],
        ),
    ]
