# Generated by Django 5.2.14 on 2026-05-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_useraccount_is_patient'),
        ('medical_app', '0003_patient_address_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduledAt']},
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-dateTime']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.RESTRICT, related_name='doctor_appointments', to='auth_app.staff'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.RESTRICT, to='auth_app.staff'),
        ),
    ]
