# Generated by Django 4.2.7 on 2026-05-10 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_patient_address_patient_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='have_encounter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encounter',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='encounter', to='medical_app.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
