# Generated by Django 4.2.7 on 2026-05-10 04:27

from django.db import migrations, models


def populate_encounter_numbers(apps, schema_editor):
    Encounter = apps.get_model('medical_app', 'Encounter')

    for number, encounter in enumerate(Encounter.objects.order_by('dateTime', 'id'), start=1):
        encounter.encounterNumber = number
        encounter.save(update_fields=['encounterNumber'])


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_appointment_have_encounter_encounter_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='encounterNumber',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_encounter_numbers, migrations.RunPython.noop),
    ]
