# Generated by Django 4.2.7 on 2026-05-10 04:36

from django.db import migrations, models
import django.db.models.deletion


def populate_missing_encounter_numbers(apps, schema_editor):
    Encounter = apps.get_model("medical_app", "Encounter")
    latest_number = (
        Encounter.objects
        .exclude(encounterNumber__isnull=True)
        .aggregate(models.Max("encounterNumber"))["encounterNumber__max"]
        or 0
    )

    for encounter in Encounter.objects.filter(encounterNumber__isnull=True).order_by("dateTime", "id"):
        latest_number += 1
        encounter.encounterNumber = latest_number
        encounter.save(update_fields=["encounterNumber"])


def point_references_to_encounter_numbers(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    reference_tables = [
        "medical_app_medicalrecordentry",
        "pharmacy_app_prescription",
        "billing_app_invoice",
    ]

    for table_name in reference_tables:
        cursor.execute(
            f"""
            UPDATE {table_name}
            SET encounter_id = (
                SELECT encounterNumber
                FROM medical_app_encounter
                WHERE medical_app_encounter.id = {table_name}.encounter_id
            )
            WHERE encounter_id IS NOT NULL
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_alter_invoice_encounter'),
        ('medical_app', '0005_encounter_encounternumber'),
        ('pharmacy_app', '0004_alter_prescription_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordentry',
            name='encounter',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='medical_app.encounter'),
        ),
        migrations.RunPython(populate_missing_encounter_numbers, migrations.RunPython.noop),
        migrations.RunPython(point_references_to_encounter_numbers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='encounter',
            name='id',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounterNumber',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
