# Generated by Django 6.0.4 on 2026-04-30 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VALIDATED', 'Validated'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('digitalSignature', models.TextField(blank=True, null=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_app.encounter')),
            ],
        ),
    ]
