# Generated by Django 4.2.7 on 2026-05-06 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_useraccount_failedloginattempts_and_more'),
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensedBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='auth_app.staff'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='validatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('VALIDATED', 'Validated'), ('DISPENSED', 'Dispensed'), ('INVALID', 'Invalid')], default='CREATED', max_length=20),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('itemId', models.CharField(max_length=50)),
                ('medicineName', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_app.prescription')),
            ],
        ),
    ]
