# Generated by Django 4.2.7 on 2026-05-10 03:12

from django.db import migrations, models
import django.db.models.deletion


def create_medicines_from_existing_items(apps, schema_editor):
    Medicine = apps.get_model('pharmacy_app', 'Medicine')
    PrescriptionItem = apps.get_model('pharmacy_app', 'PrescriptionItem')

    medicine_names = (
        PrescriptionItem.objects
        .exclude(medicineName='')
        .values_list('medicineName', flat=True)
        .distinct()
    )

    for name in medicine_names:
        Medicine.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_prescription_dispensedat_prescription_dispensedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='itemId',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunPython(create_medicines_from_existing_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicineName',
            field=models.ForeignKey(db_column='medicineName', on_delete=django.db.models.deletion.RESTRICT, to='pharmacy_app.medicine'),
        ),
    ]
