# Generated by Django 6.0.4 on 2026-04-30 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='UNPAID', max_length=20)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_app.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paidAt', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing_app.invoice')),
                ('processedBy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing_app.payment')),
            ],
        ),
    ]
