# Generated by Django 5.2.13 on 2026-05-05 10:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_useraccount_failedloginattempts_and_more'),
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEBIT', 'Debit'), ('TRANSFER', 'Transfer'), ('QRIS', 'Qris')], default='CASH', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processedBy',
            field=models.ForeignKey(limit_choices_to={'role': 'CASHIER'}, on_delete=django.db.models.deletion.RESTRICT, to='auth_app.staff'),
        ),
    ]
