# Generated by Django 5.2.13 on 2026-05-05 11:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_invoice_createdat_payment_method_alter_auditlog_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
