# Generated by Django 4.2.7 on 2026-05-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_useraccount_failedloginattempts_and_more'),
        ('billing_app', '0003_alter_invoice_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.staff'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entityId',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entityType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('VALIDATE', 'Validate Prescription'), ('DISPENSE', 'Dispense Medicine'), ('AUTH_FAIL', 'Authentication Failed'), ('ROLE_FAIL', 'Role Check Failed'), ('SIG_FAIL', 'Signature Verification Failed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='billing_app.payment'),
        ),
    ]
