# Generated by Django 5.2.14 on 2026-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_auditlog_actor_auditlog_detail_auditlog_entityid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-id']},
        ),
    ]
