# Generated by Codex on 2026-05-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_auditlog_actor_auditlog_detail_auditlog_entityid_and_more'),
        ('medical_app', '0005_encounter_encounternumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='encounter',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='medical_app.encounter'),
        ),
    ]
